### ISSUE TITLE
Add missing ErrorCallback on the canBeDisposed subscriber of the EditingContextEventProcessor

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-components#1073]
```
reactor.core.Exceptions$ErrorCallbackNotImplemented: reactor.core.Exceptions$ReactorRejectedExecutionException: Scheduler unavailable
Caused by: reactor.core.Exceptions$ReactorRejectedExecutionException: Scheduler unavailable
	at reactor.core.Exceptions.failWithRejected(Exceptions.java:267) ~[reactor-core-3.4.11.jar:3.4.11]
	at reactor.core.publisher.Operators.onRejectedExecution(Operators.java:987) ~[reactor-core-3.4.11.jar:3.4.11]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.trySchedule(FluxPublishOn.java:327) ~[reactor-core-3.4.11.jar:3.4.11]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.request(FluxPublishOn.java:266) ~[reactor-core-3.4.11.jar:3.4.11]
	at reactor.core.publisher.LambdaSubscriber.onSubscribe(LambdaSubscriber.java:119) ~[reactor-core-3.4.11.jar:3.4.11]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.onSubscribe(FluxPublishOn.java:207) ~[reactor-core-3.4.11.jar:3.4.11]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:234) ~[reactor-core-3.4.11.jar:3.4.11]
	at reactor.core.publisher.UnicastProcessor.subscribe(UnicastProcessor.java:529) ~[reactor-core-3.4.11.jar:3.4.11]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8468) ~[reactor-core-3.4.11.jar:3.4.11]
	at reactor.core.publisher.Flux.subscribeWith(Flux.java:8641) ~[reactor-core-3.4.11.jar:3.4.11]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8438) ~[reactor-core-3.4.11.jar:3.4.11]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8362) ~[reactor-core-3.4.11.jar:3.4.11]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8305) ~[reactor-core-3.4.11.jar:3.4.11]
	at org.eclipse.sirius.components.collaborative.editingcontext.EditingContextEventProcessor.acquireRepresentationEventProcessor(EditingContextEventProcessor.java:349) ~[sirius-components-collaborative-2022.01.12.jar:2022.01.12]

```

**Comment by gcoutable** [comment]
How did you get that stack trace?

**Comment by gcoutable** [comment]
Is it relevant to add a test for that?

**Comment by sbegaudeau** [comment]
I don't think so, it would be quite complex to setup and in the end, we would only discover that the error callback that we have given to reactor is called when reactor finds out that an error has occurred. Given the behavior of the callback, we would mostly be testing Reactor.
