### ISSUE TITLE
Exception when trying to export a diagram as SVG

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#1195]
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.eclipse.sirius.components.collaborative.diagrams.export.svg.EdgeExportService.exportLinePath(EdgeExportService.java:105) ~[sirius-components-collaborative-diagrams-2022.3.10.jar!/:2022.3.10]
	at org.eclipse.sirius.components.collaborative.diagrams.export.svg.EdgeExportService.exportLine(EdgeExportService.java:69) ~[sirius-components-collaborative-diagrams-2022.3.10.jar!/:2022.3.10]
	at org.eclipse.sirius.components.collaborative.diagrams.export.svg.EdgeExportService.export(EdgeExportService.java:43) ~[sirius-components-collaborative-diagrams-2022.3.10.jar!/:2022.3.10]
	at org.eclipse.sirius.components.collaborative.diagrams.export.svg.DiagramExportService.lambda$export$1(DiagramExportService.java:64) ~[sirius-components-collaborative-diagrams-2022.3.10.jar!/:2022.3.10]
	at java.base/java.lang.Iterable.forEach(Unknown Source) ~[na:na]
	at org.eclipse.sirius.components.collaborative.diagrams.export.svg.DiagramExportService.export(DiagramExportService.java:64) ~[sirius-components-collaborative-diagrams-2022.3.10.jar!/:2022.3.10]
	at org.eclipse.sirius.components.collaborative.diagrams.handlers.ExportDiagramEventHandler.handle(ExportDiagramEventHandler.java:51) ~[sirius-components-collaborative-diagrams-2022.3.10.jar!/:2022.3.10]
	at org.eclipse.sirius.components.collaborative.diagrams.DiagramEventProcessor.handle(DiagramEventProcessor.java:122) ~[sirius-components-collaborative-diagrams-2022.3.10.jar!/:2022.3.10]
	at org.eclipse.sirius.components.collaborative.editingcontext.EditingContextEventProcessor.handleRepresentationInput(EditingContextEventProcessor.java:323) ~[sirius-components-collaborative-2022.3.10.jar!/:2022.3.10]
	at org.eclipse.sirius.components.collaborative.editingcontext.EditingContextEventProcessor.doHandle(EditingContextEventProcessor.java:242) ~[sirius-components-collaborative-2022.3.10.jar!/:2022.3.10]
	at org.eclipse.sirius.components.collaborative.editingcontext.EditingContextEventProcessor.lambda$handle$2(EditingContextEventProcessor.java:211) ~[sirius-components-collaborative-2022.3.10.jar!/:2022.3.10]
	at org.eclipse.sirius.components.collaborative.requestcontext.DelegatingRequestContextRunnable.run(DelegatingRequestContextRunnable.java:40) ~[sirius-components-collaborative-2022.3.10.jar!/:2022.3.10]
	at org.springframework.security.concurrent.DelegatingSecurityContextRunnable.run(DelegatingSecurityContextRunnable.java:82) ~[spring-security-core-5.6.2.jar!/:5.6.2]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	... 1 common frames omitted
```

**Comment by pcdavid** [comment]
Seems to be related to https://github.com/eclipse-sirius/sirius-components/commit/7def1df13e88abaf63c3fcd3cfee4efef759774f#diff-3f2b8b215db497f666e84a8d10d3c8fe6b26e0c721245aada11d3e331bccd0e9R28 which (from my reading) allows for edges with no routing points at all.

@gcoutable do you think that is a possible explanation?

**Comment by gcoutable** [comment]
That is a possible explanation. Before edge anchors were the first and the last routing points. Now edge anchors are calculated from the `sourceAnchorRelativePosition` and `targetAnchorRelativePosition`. To get the exact edge start and edge end position look at `EdgeLabelPositionProvider#getCenterPosition`.
Now, routing points are used to route an edge only.
