### ISSUE TITLE
Error when trying to create the same view mutliple times using the View DSL

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#1317]
### Steps to reproduce

1. Upload [the attached modeler definition](https://github.com/eclipse-sirius/sirius-components/files/9249410/test.drop.zip). It defines a simple unsynchronized node description and a drop tool on the diagram to create the corresponding view.
2. Create a new empty project with a "drop::Root" element and a "drop::Element" inside.
3. Create a "Double drop test" diagram on the root.
4. DnD the Element from the explorer onto the diagram: the corresponding node appears as expected.
5. Try to repeat step 4: no new view is created (as expected), but the frontend becomes completely unresponsive. Even reloading the page/tab does not fix the issue (at least under Chrome).
6. Go back to the project list, try to reopen the project and diagram. You get a "The diagram does not exist" message, and on the backend's console this stack:

```
2022-08-03 10:17:46.770  WARN 24597 --- [nio-8080-exec-9] n.g.e.SimpleDataFetcherExceptionHandler  : Exception while fetching data (/diagramEvent) : Duplicate key 6ee399a0-ead9-4738-84a8-f4d4f4205066 (attempted merging values Node {id: 73f3c273-e17b-3f33-b78c-9734530b1d8d, targetObjectId: 6ee399a0-ead9-4738-84a8-f4d4f4205066, targetObjectKind: siriusComponents://semantic?domain=drop&entity=Element, targetObjectLabel: , descriptionId: 4da59356-e84f-33c8-b74c-6900da5a336f, label: , styleType: RectangularNodeStyle, borderNodeCount: 0, childNodeCount: 0} and Node {id: 73f3c273-e17b-3f33-b78c-9734530b1d8d, targetObjectId: 6ee399a0-ead9-4738-84a8-f4d4f4205066, targetObjectKind: siriusComponents://semantic?domain=drop&entity=Element, targetObjectLabel: , descriptionId: 4da59356-e84f-33c8-b74c-6900da5a336f, label: , styleType: RectangularNodeStyle, borderNodeCount: 0, childNodeCount: 0})

java.lang.IllegalStateException: Duplicate key 6ee399a0-ead9-4738-84a8-f4d4f4205066 (attempted merging values Node {id: 73f3c273-e17b-3f33-b78c-9734530b1d8d, targetObjectId: 6ee399a0-ead9-4738-84a8-f4d4f4205066, targetObjectKind: siriusComponents://semantic?domain=drop&entity=Element, targetObjectLabel: , descriptionId: 4da59356-e84f-33c8-b74c-6900da5a336f, label: , styleType: RectangularNodeStyle, borderNodeCount: 0, childNodeCount: 0} and Node {id: 73f3c273-e17b-3f33-b78c-9734530b1d8d, targetObjectId: 6ee399a0-ead9-4738-84a8-f4d4f4205066, targetObjectKind: siriusComponents://semantic?domain=drop&entity=Element, targetObjectLabel: , descriptionId: 4da59356-e84f-33c8-b74c-6900da5a336f, label: , styleType: RectangularNodeStyle, borderNodeCount: 0, childNodeCount: 0})
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133) ~[na:na]
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[na:na]
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
	at org.eclipse.sirius.components.diagrams.components.NodesRequestor.<init>(NodesRequestor.java:35) ~[classes/:na]
	at org.eclipse.sirius.components.diagrams.components.DiagramComponent.lambda$2(DiagramComponent.java:63) ~[classes/:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
	at org.eclipse.sirius.components.diagrams.components.DiagramComponent.render(DiagramComponent.java:76) ~[classes/:na]
	at org.eclipse.sirius.components.representations.BaseRenderer.renderComponent(BaseRenderer.java:200) ~[classes/:na]
	at org.eclipse.sirius.components.representations.BaseRenderer.renderElement(BaseRenderer.java:121) ~[classes/:na]
	at org.eclipse.sirius.components.diagrams.renderer.DiagramRenderer.render(DiagramRenderer.java:42) ~[classes/:na]
	at org.eclipse.sirius.components.collaborative.diagrams.DiagramCreationService.doRender(DiagramCreationService.java:129) ~[classes/:na]
	at org.eclipse.sirius.components.collaborative.diagrams.DiagramCreationService.refresh(DiagramCreationService.java:97) ~[classes/:na]
	at org.eclipse.sirius.components.collaborative.diagrams.DiagramEventProcessor.<init>(DiagramEventProcessor.java:88) ~[classes/:na]
	at org.eclipse.sirius.components.collaborative.diagrams.DiagramEventProcessorFactory.createRepresentationEventProcessor(DiagramEventProcessorFactory.java:81) ~[classes/:na]
	at org.eclipse.sirius.components.collaborative.editingcontext.RepresentationEventProcessorComposedFactory.lambda$1(RepresentationEventProcessorComposedFactory.java:51) ~[classes/:na]
	at java.base/java.util.Optional.flatMap(Optional.java:294) ~[na:na]
	at org.eclipse.sirius.components.collaborative.editingcontext.RepresentationEventProcessorComposedFactory.createRepresentationEventProcessor(RepresentationEventProcessorComposedFactory.java:51) ~[classes/:na]
	at org.eclipse.sirius.components.collaborative.editingcontext.EditingContextEventProcessor.acquireRepresentationEventProcessor(EditingContextEventProcessor.java:339) ~[classes/:na]
	at org.eclipse.sirius.web.graphql.datafetchers.subscriptions.SubscriptionDiagramEventDataFetcher.lambda$0(SubscriptionDiagramEventDataFetcher.java:69) ~[classes/:na]
	at java.base/java.util.Optional.flatMap(Optional.java:294) ~[na:na]
	at org.eclipse.sirius.web.graphql.datafetchers.subscriptions.SubscriptionDiagramEventDataFetcher.get(SubscriptionDiagramEventDataFetcher.java:69) ~[classes/:na]
	at org.eclipse.sirius.web.graphql.datafetchers.subscriptions.SubscriptionDiagramEventDataFetcher.get(SubscriptionDiagramEventDataFetcher.java:1) ~[classes/:na]
	at graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation.lambda$instrumentDataFetcher$0(DataLoaderDispatcherInstrumentation.java:87) ~[graphql-java-18.0.jar:na]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:279) ~[graphql-java-18.0.jar:na]
	at graphql.execution.SubscriptionExecutionStrategy.createSourceEventStream(SubscriptionExecutionStrategy.java:91) ~[graphql-java-18.0.jar:na]
	at graphql.execution.SubscriptionExecutionStrategy.execute(SubscriptionExecutionStrategy.java:53) ~[graphql-java-18.0.jar:na]
	at graphql.execution.Execution.executeOperation(Execution.java:160) ~[graphql-java-18.0.jar:na]
	at graphql.execution.Execution.execute(Execution.java:106) ~[graphql-java-18.0.jar:na]
	at graphql.GraphQL.execute(GraphQL.java:641) ~[graphql-java-18.0.jar:na]
	at graphql.GraphQL.lambda$parseValidateAndExecute$11(GraphQL.java:561) ~[graphql-java-18.0.jar:na]
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235) ~[na:na]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:556) ~[graphql-java-18.0.jar:na]
	at graphql.GraphQL.executeAsync(GraphQL.java:524) ~[graphql-java-18.0.jar:na]
	at graphql.GraphQL.execute(GraphQL.java:450) ~[graphql-java-18.0.jar:na]
	at org.eclipse.sirius.components.graphql.ws.handlers.StartMessageHandler.handle(StartMessageHandler.java:94) ~[classes/:na]
...
```

### Expected behavior

The second drop should be at least a no-op, or ideally display a message like "This element is already visible on the diagram".

**Comment by adaussy** [comment]
@pcdavid I have the impression this bug has been fixed. I can no longer reproduce in my project.
Could you confirm that something has changed?

Moreover, I did not succeed in uploading your project on staging to test in a pure Sirius Component env.

**Comment by pcdavid** [comment]
I confirm that I can not reproduce anymore (after tweaking the models in the zip archive to be compatible with current master). No idea which change fixed the problem though (and no time to investigate further at the moment).
