### ISSUE TITLE
"IllegalArgumentException: resolve against non-hierarchical or relative base" when using dynamic model instances

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-components#397]
```

java.lang.IllegalArgumentException: resolve against non-hierarchical or relative base
	at org.eclipse.emf.common.util.URI$Hierarchical.resolve(URI.java:3548) ~[org.eclipse.emf.common-2.21.0.jar:na]
	at org.eclipse.emf.common.util.URI.resolve(URI.java:5580) ~[org.eclipse.emf.common-2.21.0.jar:na]
	at org.eclipse.sirius.emfjson.utils.JsonHelper.resolve(JsonHelper.java:928) ~[org.eclipse.sirius.emfjson-2.3.0-SNAPSHOT.jar:na]
	at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.getPackageForURI(GsonEObjectDeserializer.java:677) ~[org.eclipse.sirius.emfjson-2.3.0-SNAPSHOT.jar:na]
	at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.getEClass(GsonEObjectDeserializer.java:885) ~[org.eclipse.sirius.emfjson-2.3.0-SNAPSHOT.jar:na]
	at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.loadObject(GsonEObjectDeserializer.java:366) ~[org.eclipse.sirius.emfjson-2.3.0-SNAPSHOT.jar:na]
	at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserializeContent(GsonEObjectDeserializer.java:270) ~[org.eclipse.sirius.emfjson-2.3.0-SNAPSHOT.jar:na]
	at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserialize(GsonEObjectDeserializer.java:253) ~[org.eclipse.sirius.emfjson-2.3.0-SNAPSHOT.jar:na]
	at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserialize(GsonEObjectDeserializer.java:1) ~[org.eclipse.sirius.emfjson-2.3.0-SNAPSHOT.jar:na]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.6.jar:na]
	at org.eclipse.sirius.emfjson.resource.JsonResourceImpl.doLoad(JsonResourceImpl.java:299) ~[org.eclipse.sirius.emfjson-2.3.0-SNAPSHOT.jar:na]
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563) ~[org.eclipse.emf.ecore-2.23.0.jar:na]
	at org.eclipse.sirius.web.emf.services.EditingContextEPackageService.getEPackages(EditingContextEPackageService.java:71) ~[classes/:na]

```

**Comment by pcdavid** [comment]
### Analysis

The error occurs because for discovering dynamically contributed domains and views, at several points in the code we try and load *all* documents in the database as EMF models:
* `org.eclipse.sirius.web.emf.view.DynamicRepresentationDescriptionService.findDynamicRepresentationDescriptions(UUID)`
* `org.eclipse.sirius.web.emf.services.EditingContextSearchService.findById(UUID)`
* `org.eclipse.sirius.web.emf.services.EditingContextEPackageService.getEPackages(UUID)`

For most documents which are instances of statically known metamodels (including views and domain *definitions*), this is fine.
For documents which are *instances* of dynamically contributed domains, EMF JSON does not (and can not) know about the corresponding metamodel/`EPackage`, so it tries to resolve the declared nsURI, but in this case the nsURI is an UUID and fails to parse as a URI.
The problem is not the "shape" of the nsURI though, even if we used a syntactically correct nsURI, it can simply not be resolved at this point as the EMF EPackage is not known in this context.

### Proposed fix

Following @sbegaudeau's suggestion, we will add a finer grained query on `DocumentRepository`. In the locations mentioned above we are only actually interested in either domain or view definitions, so we can restrict our search and avoid trying to load problematic documents. This will also improve performance.

PostgreSQL provides the required features to find the JSON documents which are instances of specific metamodels we are interested in. For example to select (and load) only domain definitions:

```sql
SELECT * FROM Document document
WHERE document.content::jsonb @> '{ "ns": { "domain": "http://www.eclipse.org/sirius-web/domain" } }'::jsonb
```

**Comment by pcdavid** [comment]
Steps to reproduce:

1. Make sure you have registered the domain & view metamodels.
2. Start Sirius Web
3. Create a new project, say "studio".
4. In it create a new domain definition with at least one entity type.
5. Go back to the project list and create a separate project, say "instance"
6. In it, create a new empty document. Creating an "Empty Flow" and removing the top-level System afterwards is OK too.
7. On the new document do "New Object", and in the "Create a new root object" dialog, select the domain created at step 4 above in "studio", and chose any of its entity type.
8. The dynamic instance is created correctly, but as as soon as you select it in the explorer you get the following error in the backend logs:

```
java.lang.IllegalArgumentException: resolve against non-hierarchical or relative base
	at org.eclipse.emf.common.util.URI$Hierarchical.resolve(URI.java:3548) ~[org.eclipse.emf.common-2.21.0.jar:na]
	at org.eclipse.emf.common.util.URI.resolve(URI.java:5580) ~[org.eclipse.emf.common-2.21.0.jar:na]
	at org.eclipse.sirius.emfjson.utils.JsonHelper.resolve(JsonHelper.java:928) ~[org.eclipse.sirius.emfjson-2.3.0-SNAPSHOT.jar:na]
	at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.getPackageForURI(GsonEObjectDeserializer.java:677) ~[org.eclipse.sirius.emfjson-2.3.0-SNAPSHOT.jar:na]
	at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.getEClass(GsonEObjectDeserializer.java:885) ~[org.eclipse.sirius.emfjson-2.3.0-SNAPSHOT.jar:na]
	at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.loadObject(GsonEObjectDeserializer.java:366) ~[org.eclipse.sirius.emfjson-2.3.0-SNAPSHOT.jar:na]
	at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserializeContent(GsonEObjectDeserializer.java:270) ~[org.eclipse.sirius.emfjson-2.3.0-SNAPSHOT.jar:na]
	at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserialize(GsonEObjectDeserializer.java:253) ~[org.eclipse.sirius.emfjson-2.3.0-SNAPSHOT.jar:na]
	at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserialize(GsonEObjectDeserializer.java:1) ~[org.eclipse.sirius.emfjson-2.3.0-SNAPSHOT.jar:na]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.6.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.6.jar:na]
	at org.eclipse.sirius.emfjson.resource.JsonResourceImpl.doLoad(JsonResourceImpl.java:299) ~[org.eclipse.sirius.emfjson-2.3.0-SNAPSHOT.jar:na]
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563) ~[org.eclipse.emf.ecore-2.23.0.jar:na]
	at org.eclipse.sirius.web.emf.services.EditingContextEPackageService.getEPackages(EditingContextEPackageService.java:73) ~[classes/:na]
	at org.eclipse.sirius.web.emf.services.EditService.getPackageRegistry(EditService.java:101) ~[classes/:na]
	at org.eclipse.sirius.web.emf.services.EditService.findClass(EditService.java:81) ~[classes/:na]
	at org.eclipse.sirius.web.graphql.datafetchers.editingcontext.EditingContextRepresentationDescriptionsDataFetcher.get(EditingContextRepresentationDescriptionsDataFetcher.java:72) ~[classes/:na]
```

The stack is slightly different from the first one above, here it's the onboarding area which asks for the `editingContext { representationDescription }`, and the corresponding data fetcher which tries to load all documents in the db, include the newly created dynamic instance, in an EMF context where the corresponding EPackag is not known.
