### ISSUE TITLE
NPE when trying to download/export a project with dynamic instances

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#431]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** : master
* [x] **I have specified my environment** : Linux

When a project contains a document which is an instance of a dynamically-defined domain (in another project on the same instance), the export fails and the client gets an ugly Java stack trace in the browser:

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon Apr 12 16:43:09 CEST 2021
There was an unexpected error (type=Internal Server Error, status=500).
No message available
java.lang.NullPointerException
	at org.eclipse.sirius.web.emf.services.EObjectIDManager.findAdapter(EObjectIDManager.java:108)
	at org.eclipse.sirius.web.emf.services.EObjectIDManager.findId(EObjectIDManager.java:59)
	at org.eclipse.sirius.emfjson.resource.JsonResourceImpl.setID(JsonResourceImpl.java:435)
	at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.loadObject(GsonEObjectDeserializer.java:376)
	at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserializeContent(GsonEObjectDeserializer.java:270)
	at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserialize(GsonEObjectDeserializer.java:253)
	at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserialize(GsonEObjectDeserializer.java:1)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at org.eclipse.sirius.emfjson.resource.JsonResourceImpl.doLoad(JsonResourceImpl.java:299)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563)
	at org.eclipse.sirius.web.emf.services.ProjectExportService.loadAllDocuments(ProjectExportService.java:284)
	at org.eclipse.sirius.web.emf.services.ProjectExportService.addRepresentation(ProjectExportService.java:206)
	at org.eclipse.sirius.web.emf.services.ProjectExportService.toZip(ProjectExportService.java:122)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.eclipse.sirius.web.emf.services.ProjectExportService.exportProjectAsZip(ProjectExportService.java:109)
	at org.eclipse.sirius.web.spring.controllers.ProjectController.getProject(ProjectController.java:76)
```

**Comment by pcdavid** [comment]
Fixed by #528
