### ISSUE TITLE
Representations on objects which no longer exist are not cleaned up and can still appear in the onboard area

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#452]
I'm not entirely sure of the steps to reproduce yet but I had 2 diagrams inside my project, I deleted them both, closed the tabs, and the onboard area still displays one as existing, with a link to open it (which fails).
Every refreshing the page, or going back to the project browser and re-opening still displays the non-existent diagram as available.

![2021-04-23_09-16](https://user-images.githubusercontent.com/10608/115833671-9ae60880-a414-11eb-9f79-2710a9a63ceb.png)

**Comment by pcdavid** [comment]
Actually, looking at the underlying database it looks like the diagram *does* exist, and the link from the onboard area points to the correct project/editing context id _and_ correct representation id, but I get "An error has occured while trying to retrieve the diagram" and the diagram editor says "The diagram does not exist".

Maybe the issue is elsewhere and the "The diagram does not exist" error message is actually wrong.

**Comment by pcdavid** [comment]
Looking at the server logs it seem the issue is unrelated to the onboard area, but more an NPE while trying to update the diagram (which does exist):

```
2021-04-23 07:29:05.335  WARN 19027 --- [nio-5000-exec-3] n.g.e.SimpleDataFetcherExceptionHandler  : Exception while fetching data (/diagramEvent) : null
java.lang.NullPointerException: null
at java.base/java.util.Objects.requireNonNull(Objects.java:221) ~[na:na]
at org.eclipse.sirius.web.spring.collaborative.diagrams.DiagramContext.update(DiagramContext.java:49) ~[sirius-web-spring-collaborative-diagrams-0.2.19.jar!/:0.2.19]
at org.eclipse.sirius.web.spring.collaborative.diagrams.DiagramEventProcessor.<init>(DiagramEventProcessor.java:84) ~[sirius-web-spring-collaborative-diagrams-0.2.19.jar!/:0.2.19]
at org.eclipse.sirius.web.spring.collaborative.diagrams.DiagramEventProcessorFactory.createRepresentationEventProcessor(DiagramEventProcessorFactory.java:73) ~[sirius-web-spring-collaborative-diagrams-0.2.19.jar!/:0.2.19]
at org.eclipse.sirius.web.spring.collaborative.projects.RepresentationEventProcessorComposedFactory.lambda$createRepresentationEventProcessor$1(RepresentationEventProcessorComposedFactory.java:51) ~[sirius-web-spring-collaborative-0.2.19.jar!/:0.2.19]
at java.base/java.util.Optional.flatMap(Optional.java:294) ~[na:na]
at org.eclipse.sirius.web.spring.collaborative.projects.RepresentationEventProcessorComposedFactory.createRepresentationEventProcessor(RepresentationEventProcessorComposedFactory.java:51) ~[sirius-web-spring-collaborative-0.2.19.jar!/:0.2.19]
at org.eclipse.sirius.web.spring.collaborative.projects.EditingContextEventProcessor.acquireRepresentationEventProcessor(EditingContextEventProcessor.java:315) ~[sirius-web-spring-collaborative-0.2.19.jar!/:0.2.19]
at org.eclipse.sirius.web.spring.collaborative.diagrams.graphql.SubscriptionDiagramEventDataFetcher.lambda$get$0(SubscriptionDiagramEventDataFetcher.java:79) ~[sirius-web-spring-collaborative-diagrams-0.2.19.jar!/:0.2.19]
at java.base/java.util.Optional.flatMap(Optional.java:294) ~[na:na]
at org.eclipse.sirius.web.spring.collaborative.diagrams.graphql.SubscriptionDiagramEventDataFetcher.get(SubscriptionDiagramEventDataFetcher.java:79) ~[sirius-web-spring-collaborative-diagrams-0.2.19.jar!/:0.2.19]
at org.eclipse.sirius.web.spring.collaborative.diagrams.graphql.SubscriptionDiagramEventDataFetcher.get(SubscriptionDiagramEventDataFetcher.java:50) ~[sirius-web-spring-collaborative-diagrams-0.2.19.jar!/:0.2.19]
at graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation.lambda$instrumentDataFetcher$0(DataLoaderDispatcherInstrumentation.java:86) ~[graphql-java-16.1.jar!/:na]
at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270) ~[graphql-java-16.1.jar!/:na]
at graphql.execution.SubscriptionExecutionStrategy.createSourceEventStream(SubscriptionExecutionStrategy.java:91) ~[graphql-java-16.1.jar!/:na]
at graphql.execution.SubscriptionExecutionStrategy.execute(SubscriptionExecutionStrategy.java:53) ~[graphql-java-16.1.jar!/:na]
at graphql.execution.Execution.executeOperation(Execution.java:165) ~[graphql-java-16.1.jar!/:na]
at graphql.execution.Execution.execute(Execution.java:104) ~[graphql-java-16.1.jar!/:na]
at graphql.GraphQL.execute(GraphQL.java:557) ~[graphql-java-16.1.jar!/:na]
at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:482) ~[graphql-java-16.1.jar!/:na]
at graphql.GraphQL.executeAsync(GraphQL.java:446) ~[graphql-java-16.1.jar!/:na]
at graphql.GraphQL.execute(GraphQL.java:377) ~[graphql-java-16.1.jar!/:na]
```

**Comment by pcdavid** [comment]
So I think I understand the issue, and it is not really related to the onboarding area, altough it _could_ be modified to workaround the underlying issue until it is properly fixed.
The root of the issue is that when we delete model elements, we do not delete "orphan" representations which point to them (as their `targetObjectId`. These stay in the database, and because the onboarding area's query does not check for this it finds and displays them. 
Then on open in `DiagramCreationService.refresh(IEditingContext, IDiagramContext)`, the test for
```java
if (optionalObject.isPresent() && optionalDiagramDescription.isPresent()) {
```
is false because the `optionalObject` no longer exists. `refresh` returns `Optional.empty()`, and in `DiagramEventProcessor` we pass `null` to `DiagramContext.update()` in this case:

```java
        Diagram diagram = this.diagramCreationService.refresh(editingContext, diagramContext).orElse(null);
        diagramContext.update(diagram);
```

There are actually (at least) 4 issues:
* the two lines above in `DiagramEventProcessor` are broken: we explicitly transform an empty optional into `null` to pass it to a method which does not accept `null`;
* the onboarding area should be more strict in what it displays (but that is more of a workaround, and given that its content is not dynamic it could display a valid representation at a time _t_ which has become invalid at _t+n_ when the user tries to open it;
* the error message displayed in case an error occurs while opening a representation is probably too generic;
* the underlying issue is that we should remove representations which have become invalid because their target object no longer exists. When and how to do this without disrupting the user's workflow (which may have the representation opened at the time) will require some thought.

**Comment by gcoutable** [comment]
It seems to be a clone of https://github.com/eclipse-sirius/sirius-components/issues/380
