### ISSUE TITLE
The node and edge direct edit does not work because the label id are not UUID anymore

### ISSUE THREAD

**Issue by Camork** [eclipse-sirius/sirius-components#852]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest v0.5.5
* [ ] **I have specified my environment** : 
- MAC

````
Caused by: java.lang.IllegalArgumentException: UUID string too large
	at java.base/java.util.UUID.fromString(UUID.java:199) ~[na:na]
	at org.eclipse.sirius.web.spring.collaborative.diagrams.handlers.EditLabelEventHandler.handle(EditLabelEventHandler.java:104) ~[classes/:na]
	at org.eclipse.sirius.web.spring.collaborative.diagrams.DiagramEventProcessor.handle(DiagramEventProcessor.java:128) ~[classes/:na]
	at org.eclipse.sirius.web.spring.collaborative.projects.EditingContextEventProcessor.handleRepresentationInput(EditingContextEventProcessor.java:307) ~[classes/:na]
	at org.eclipse.sirius.web.spring.collaborative.projects.EditingContextEventProcessor.doHandle(EditingContextEventProcessor.java:226) ~[classes/:na]
	at org.eclipse.sirius.web.spring.collaborative.projects.EditingContextEventProcessor.lambda$handle$3(EditingContextEventProcessor.java:195) ~[classes/:na]
	at org.springframework.security.concurrent.DelegatingSecurityContextRunnable.run(DelegatingSecurityContextRunnable.java:82) ~[spring-security-core-5.5.3.jar:5.5.3]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	... 1 common frames omitted
````

**Comment by sbegaudeau** [comment]
We have started working on this issue, it has been caused by the change of diagram element id type from UUID to String. A fix will arrive soon on master (maybe tomorrow).
