### ISSUE TITLE
It is possible to create instances of the `NamedElement` type in `domain.ecore` but they can not be displayed

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-components#885]
### Steps to reproduce

1. Create a new project.
2. Create a _Domain_ model inside.
3. On the context menu of the _Domain_ model itself (not the automatically create element inside), select _New Object_
4. Choose `http://www.eclipse.org/sirius-web/domain` as domain and uncheck the "Show only suggested root types" checkbox
5. The object type selected is "Named Element". This is the first bug 🐛: `NamedElement` should be abstract and not proposed here
6. Click on "Create". Nothing is visible in the explorer, with no error feedback. There is a stacktrace in the backend 🐛:

```
java.util.MissingResourceException: The image resource 'full/obj16/NamedElement' could not be located
	at org.eclipse.emf.common.util.DelegatingResourceLocator.delegatedGetImage(DelegatingResourceLocator.java:388) ~[org.eclipse.emf.common-2.21.0.jar:na]
	at org.eclipse.emf.common.util.DelegatingResourceLocator.getImage(DelegatingResourceLocator.java:303) ~[org.eclipse.emf.common-2.21.0.jar:na]
	at org.eclipse.sirius.web.domain.provider.NamedElementItemProvider.getImage(NamedElementItemProvider.java:85) ~[classes/:na]
	at org.eclipse.sirius.web.emf.services.ObjectService.getImagePath(ObjectService.java:150) ~[classes/:na]
	at org.eclipse.sirius.web.services.explorer.ExplorerDescriptionProvider.getImageURL(ExplorerDescriptionProvider.java:180) ~[classes/:na]
	at org.eclipse.sirius.web.trees.renderer.TreeRenderer.renderTreeItem(TreeRenderer.java:71) ~[classes/:na]
	at org.eclipse.sirius.web.trees.renderer.TreeRenderer.renderTreeItem(TreeRenderer.java:79) ~[classes/:na]
	at org.eclipse.sirius.web.trees.renderer.TreeRenderer.render(TreeRenderer.java:51) ~[classes/:na]
	at org.eclipse.sirius.web.spring.collaborative.trees.TreeService.create(TreeService.java:40) ~[classes/:na]
	at org.eclipse.sirius.web.spring.collaborative.trees.TreeEventProcessor.refreshTree(TreeEventProcessor.java:178) ~[classes/:na]
	at org.eclipse.sirius.web.spring.collaborative.trees.TreeEventProcessor.refresh(TreeEventProcessor.java:130) ~[classes/:na]
```

**Comment by pcdavid** [comment]
There are two different issues:

1. `NamedElement` should be abstract (it was meant to be).
2. The backend should be more robust to this kind of exception, which can happen in case of packaging issues (or plain missing icons).
