### ISSUE TITLE
IndexOutOfBounds while computing the position of the label of an edge

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-components#948]
In `EdgeLabelPositionProvider`, we are checking if there are at least 2 routing points but we are using `routingPoints.get(2)` just after. We should either use `routingPoints.get(0)` and `routingPoints.get(1)` instead of `routingPoints.get(1)` and `routingPoints.get(2)` or check that there are at least three routing points.

**Comment by sbegaudeau** [comment]
```
java.lang.IndexOutOfBoundsException: Index: 2 Size: 2
	at java.base/java.util.ImmutableCollections$AbstractImmutableList.outOfBounds(ImmutableCollections.java:333) ~[na:na]
	at java.base/java.util.ImmutableCollections$List12.get(ImmutableCollections.java:585) ~[na:na]
	at org.eclipse.sirius.web.diagrams.layout.incremental.provider.EdgeLabelPositionProvider.getCenterPosition(EdgeLabelPositionProvider.java:51) ~[classes/:na]
	at org.eclipse.sirius.web.diagrams.layout.incremental.IncrementalLayoutEngine.layoutEdge(IncrementalLayoutEngine.java:174) ~[classes/:na]
	at org.eclipse.sirius.web.diagrams.layout.incremental.IncrementalLayoutEngine.layout(IncrementalLayoutEngine.java:89) ~[classes/:na]
	at org.eclipse.sirius.web.diagrams.layout.LayoutService.incrementalLayout(LayoutService.java:141) ~[classes/:na]
	at org.eclipse.sirius.web.spring.collaborative.diagrams.DiagramCreationService.doRender(DiagramCreationService.java:133) ~[classes/:na]
```

**Comment by pcdavid** [comment]
I can trigger this when trying to create an edge-to-self on a domain diagram. After that, the diagram seems broken: auto-layout does nothing (with no feeback:error on the front or back), and I can not delete the diagram.
